name: CI Pipeline 
 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ] 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
    - uses: actions/checkout@v3 
 
    - name: Run a simple command 
      run: echo "Hello, GitHub Actions! CI pipeline is working." 
